// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeO5m6EPrEShpfn959C10MFfWCnuq6wf8',
    appId: '1:529238803141:web:3cdf61c0c79e175571e6ac',
    messagingSenderId: '529238803141',
    projectId: 'preloved-market',
    authDomain: 'preloved-market.firebaseapp.com',
    storageBucket: 'preloved-market.firebasestorage.app',
    measurementId: 'G-9S7CSHM1V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4n_zwmFXlM1q3HvW9hOenqzwQrLvh-m0',
    appId: '1:529238803141:android:cdd746f8a29cd0ed71e6ac',
    messagingSenderId: '529238803141',
    projectId: 'preloved-market',
    storageBucket: 'preloved-market.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuMOIIzQGL0bgAYvxY6vvBZhb5wX7TLxQ',
    appId: '1:529238803141:ios:3d8f4e19e3bc544071e6ac',
    messagingSenderId: '529238803141',
    projectId: 'preloved-market',
    storageBucket: 'preloved-market.firebasestorage.app',
    iosClientId: '529238803141-gdhh5h1s5227n4v2ng8aqjhno5ibhdd8.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuMOIIzQGL0bgAYvxY6vvBZhb5wX7TLxQ',
    appId: '1:529238803141:ios:3d8f4e19e3bc544071e6ac',
    messagingSenderId: '529238803141',
    projectId: 'preloved-market',
    storageBucket: 'preloved-market.firebasestorage.app',
    iosClientId: '529238803141-gdhh5h1s5227n4v2ng8aqjhno5ibhdd8.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeO5m6EPrEShpfn959C10MFfWCnuq6wf8',
    appId: '1:529238803141:web:ecf1793cc6d7c5ba71e6ac',
    messagingSenderId: '529238803141',
    projectId: 'preloved-market',
    authDomain: 'preloved-market.firebaseapp.com',
    storageBucket: 'preloved-market.firebasestorage.app',
    measurementId: 'G-R5NXEDKVXW',
  );
}
