import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'app_name': 'PreLoved Market',
      'login': 'Login',
      'signup': 'Sign Up',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'create_account': 'Create an account',
      'hello': 'Hello!!',
      'search_hint': 'Search for clothes, shoes...',
      'todays_pick': "Today's Pick",
      'see_all': 'See all',
      'sell_item': 'Sell Item',
      'post_listing': 'POST LISTING',
      'messages': 'Messages',
      'profile': 'Profile',
      'settings': 'Settings',
      'help_support': 'Help & Support',
      'edit_profile': 'Edit Profile',
      'my_addresses': 'My Addresses',
      'purchase_history': 'Purchase History',
      'logout': 'Logout',
      'cart': 'Shopping Cart',
      'cart_empty': 'Your cart is empty',
      'no_listings': 'No listings yet',
      'no_history': 'No purchase history',
      'no_addresses': 'No addresses saved',
      'start_shopping': 'Start Shopping',
      'back_to_home': 'Back to Home',
      'message_seller': 'MESSAGE SELLER',
      'description': 'Description',
      'condition': 'Condition',
      'price': 'Price',
      'size': 'Size',
      'location': 'Location',
      'category': 'Category',
      'title': 'Title',
      'save_changes': 'Save Changes',
      'delete_account': 'Delete Account',
      'privacy_policy': 'Privacy Policy',
      'language': 'Language',
      'notifications': 'Push Notifications',
      'dark_mode': 'Dark Mode',
      'change_password': 'Change Password',
      'general': 'General',
      'account': 'Account',
      'danger_zone': 'Danger Zone',
      'cancel': 'Cancel',
      'logout_confirmation': 'Are you sure you want to logout?',
      'listings': 'Listings',
      'sold': 'Sold',
      'rating': 'Rating',
      'my_listings': 'My Listings',
      'post_your_first_item': 'Post your first item',
      'shopping_cart': 'Shopping Cart',
      'browse_items_add_to_cart': 'Browse items and add them to your cart',
      'browse_items': 'Browse Items',
      'search': 'Search',
      'start_typing_search': 'Start typing to search',
      'no_results_found': 'No results found',
      'post': 'POST',
      'tap_to_upload_photos': 'Tap to Upload Photos (JPG, PNG)',
      'minimum_photos': '(Minimum 1 required)',
      'uploading_images': 'Uploading images...',
      'listing_posted': 'Listing Posted!',
      'listing_posted_message': 'has been posted successfully.',
      'post_first_listing': 'Post the first listing!',
      'promo_title': 'Get Your FAV',
      'promo_subtitle': 'in no time. easy access!',
      'profile_updated': 'Profile updated!',
      'full_name': 'Full Name',
      'phone': 'Phone',
      'campus': 'Campus',
      'add_address': 'Add Address',
      'tap_to_add_address': 'Tap + to add your campus address',
      'save': 'Save',
      'no_addresses_saved': 'No addresses saved',
      'your_completed_purchases_will_appear_here': 'Your completed purchases will appear here',
      'delete_account_permanently': 'Delete Account Permanently?',
      'this_action_permanent': 'This action is permanent. All your data, listings, and messages will be deleted forever.',
      'enter_password_to_confirm': 'Enter your password to confirm',
      'delete_forever': 'Delete Forever',
      'forgot_password_title': 'Forgot\nPassword?',
      'forgot_password_subtitle': "No worries, we'll send you reset instructions",
      'back_to_login': 'Back to Login',
      'please_enter_email': 'Please enter your email',
      'password_reset_email_sent': 'Password reset email sent!',
      'search_clothes_shoes_accessories': 'Search clothes, shoes, accessories...',
      'seller': 'Seller',
      'size_label': 'Size:',
      'description_label': 'DESCRIPTION:',
      'posted_label': 'Posted',
      'no_items_sold_yet': 'No items sold yet',
      'no_ratings_yet': 'No ratings yet',
    },
    'fr': {
      'app_name': 'PreLoved Market',
      'login': 'Connexion',
      'signup': "S'inscrire",
      'email': 'E-mail',
      'password': 'Mot de passe',
      'forgot_password': 'Mot de passe oublié?',
      'create_account': 'Créer un compte',
      'hello': 'Bonjour!!',
      'search_hint': 'Rechercher des vêtements, chaussures...',
      'todays_pick': "Choix du jour",
      'see_all': 'Voir tout',
      'sell_item': 'Vendre un article',
      'post_listing': 'PUBLIER',
      'messages': 'Messages',
      'profile': 'Profil',
      'settings': 'Paramètres',
      'help_support': 'Aide et support',
      'edit_profile': 'Modifier le profil',
      'my_addresses': 'Mes adresses',
      'purchase_history': "Historique d'achats",
      'logout': 'Déconnexion',
      'cart': 'Panier',
      'cart_empty': 'Votre panier est vide',
      'no_listings': 'Aucune annonce',
      'no_history': "Aucun historique d'achat",
      'no_addresses': 'Aucune adresse enregistrée',
      'start_shopping': 'Commencer les achats',
      'back_to_home': "Retour à l'accueil",
      'message_seller': 'CONTACTER LE VENDEUR',
      'description': 'Description',
      'condition': 'État',
      'price': 'Prix',
      'size': 'Taille',
      'location': 'Emplacement',
      'category': 'Catégorie',
      'title': 'Titre',
      'save_changes': 'Enregistrer',
      'delete_account': 'Supprimer le compte',
      'privacy_policy': 'Politique de confidentialité',
      'language': 'Langue',
      'notifications': 'Notifications',
      'dark_mode': 'Mode sombre',
      'change_password': 'Changer le mot de passe',
      'general': 'Général',
      'account': 'Compte',
      'danger_zone': 'Zone de danger',
      'cancel': 'Annuler',
      'logout_confirmation': 'Voulez-vous vraiment vous déconnecter?',
      'listings': 'Annonces',
      'sold': 'Vendu',
      'rating': 'Note',
      'my_listings': 'Mes annonces',
      'post_your_first_item': 'Publiez votre premier article',
      'shopping_cart': 'Panier',
      'browse_items_add_to_cart': 'Parcourez les articles et ajoutez-les à votre panier',
      'browse_items': 'Parcourir',
      'search': 'Recherche',
      'start_typing_search': 'Commencez à taper pour rechercher',
      'no_results_found': 'Aucun résultat trouvé',
      'post': 'PUBLIER',
      'tap_to_upload_photos': 'Appuyez pour télécharger des photos (JPG, PNG)',
      'minimum_photos': '(Minimum 1 requis)',
      'uploading_images': 'Téléchargement des images...',
      'listing_posted': 'Annonce publiée!',
      'listing_posted_message': 'a été publiée avec succès.',
      'post_first_listing': 'Publiez la première annonce!',
      'promo_title': 'Obtenez votre FAV',
      'promo_subtitle': 'en un rien de temps. accès facile!',
      'profile_updated': 'Profil mis à jour!',
      'full_name': 'Nom complet',
      'phone': 'Téléphone',
      'campus': 'Campus',
      'add_address': 'Ajouter une adresse',
      'tap_to_add_address': 'Appuyez sur + pour ajouter votre adresse de campus',
      'save': 'Enregistrer',
      'no_addresses_saved': 'Aucune adresse enregistrée',
      'your_completed_purchases_will_appear_here': 'Vos achats terminés apparaîtront ici',
      'delete_account_permanently': 'Supprimer le compte définitivement?',
      'this_action_permanent': 'Cette action est permanente. Toutes vos données, annonces et messages seront supprimés définitivement.',
      'enter_password_to_confirm': 'Entrez votre mot de passe pour confirmer',
      'delete_forever': 'Supprimer définitivement',
      'forgot_password_title': 'Mot de passe\noublié?',
      'forgot_password_subtitle': 'Pas de souci, nous vous enverrons des instructions de réinitialisation',
      'back_to_login': 'Retour à la connexion',
      'please_enter_email': 'Veuillez saisir votre e-mail',
      'password_reset_email_sent': 'E-mail de réinitialisation envoyé!',
      'search_clothes_shoes_accessories': 'Recherchez vêtements, chaussures, accessoires...',
      'seller': 'Vendeur',
      'size_label': 'Taille :',
      'description_label': 'DESCRIPTION :',
      'posted_label': 'Publié',
      'no_items_sold_yet': 'Aucun article vendu pour le moment',
      'no_ratings_yet': 'Pas encore de notes',
    },
    'rw': {
      'app_name': 'PreLoved Market',
      'login': 'Injira',
      'signup': 'Iyandikishe',
      'email': 'Imeyili',
      'password': 'Ijambo ryibanga',
      'forgot_password': 'Wibagiwe ijambo ryibanga?',
      'create_account': 'Fungura konti',
      'hello': 'Muraho!!',
      'search_hint': 'Shakisha imyambaro, inkweto...',
      'todays_pick': "Ibyo twahisemo uyu munsi",
      'see_all': 'Reba byose',
      'sell_item': 'Gurisha igicuruzwa',
      'post_listing': 'OHEREZA',
      'messages': 'Ubutumwa',
      'profile': 'Umwirondoro',
      'settings': 'Igenamiterere',
      'help_support': 'Ubufasha',
      'edit_profile': 'Hindura umwirondoro',
      'my_addresses': 'Aderesi zanjye',
      'purchase_history': 'Amateka yo kugura',
      'logout': 'Sohoka',
      'cart': 'Agaseke',
      'cart_empty': 'Agaseke kawe ni karangaye',
      'no_listings': 'Nta bicuruzwa',
      'no_history': 'Nta mateka yo kugura',
      'no_addresses': 'Nta deresi yabitswe',
      'start_shopping': 'Tangira kugura',
      'back_to_home': 'Subira ahabanza',
      'message_seller': 'ANDIKIRA UWAGURISHA',
      'description': 'Ibisobanuro',
      'condition': 'Imiterere',
      'price': 'Igiciro',
      'size': 'Ingano',
      'location': 'Aho biherereye',
      'category': 'Icyiciro',
      'title': 'Izina',
      'save_changes': 'Bika impinduka',
      'delete_account': 'Siba konti',
      'privacy_policy': 'Politiki y\'ibanga',
      'language': 'Ururimi',
      'notifications': 'Imenyesha',
      'dark_mode': 'Uburyo bwijimye',
      'change_password': 'Hindura ijambo ryibanga',
      'general': 'Rusange',
      'account': 'Konti',
      'danger_zone': 'Ahantu habi',
      'cancel': 'Hagarika',
      'logout_confirmation': 'Urabisabye koko gusohoka?',
      'listings': 'Amashusho',
      'sold': 'Yagurishijwe',
      'rating': 'Inyenyeri',
      'my_listings': 'Amashusho yanjye',
      'post_your_first_item': 'Ohereza igicuruzwa cya mbere',
      'shopping_cart': 'Agaseke',
      'browse_items_add_to_cart': 'Shakisha ibicuruzwa ubishyire mu gaseke',
      'browse_items': 'Shakisha',
      'search': 'Shakisha',
      'start_typing_search': 'Tangira kwandika ushakisha',
      'no_results_found': 'Nta bisubizo byabonetse',
      'post': 'OHEREZA',
      'tap_to_upload_photos': 'Kanda hano wongere amafoto (JPG, PNG)',
      'minimum_photos': '(Byibuze 1 isabwa)',
      'uploading_images': 'Kohereza amafoto...',
      'listing_posted': 'Icyamamaza cyoherejwe!',
      'listing_posted_message': 'cyoherejwe neza.',
      'post_first_listing': 'Ohereza icyamamaza cya mbere!',
      'promo_title': 'Fata FAV yawe',
      'promo_subtitle': 'mu gihe gito. uburenganzira bworoshye!',
      'profile_updated': 'Umwirondoro wavuguruwe!',
      'full_name': 'Amazina yose',
      'phone': 'Telefoni',
      'campus': 'Kamupasi',
      'add_address': 'Ongeramo aderesi',
      'tap_to_add_address': 'Kanda + wongere aderesi ya campus yawe',
      'save': 'Bika',
      'no_addresses_saved': 'Nta aderesi yabitswe',
      'your_completed_purchases_will_appear_here': 'Amafaranga yaguze azagaragara hano',
      'delete_account_permanently': 'Siba konti burundu?',
      'this_action_permanent': 'Iki gikorwa kirahoraho. Amakuru yawe yose, amashusho, nâ€™ubutumwa bizasibangwa burundu.',
      'enter_password_to_confirm': 'Andika ijambo ryibanga kugira ngo wemeze',
      'delete_forever': 'Siba burundu',
      'forgot_password_title': 'Wibagiwe\nIjambo ryibanga?',
      'forgot_password_subtitle': 'Ntukabure, tuzagusangiza amabwiriza yo gusubiramo',
      'back_to_login': 'Subira mu kwinjira',
      'please_enter_email': 'Injiza email yawe',
      'password_reset_email_sent': 'Imeri yo gusubiramo yoherejwe!',
      'search_clothes_shoes_accessories': 'Shakisha imyenda, inkweto, ibikoresho...',
      'seller': 'Uwagurishije',
      'size_label': 'Ingano :',
      'description_label': 'IBISOBANURO :',
      'posted_label': 'Byashyizwe ku rubuga',
      'no_items_sold_yet': 'Nta bicuruzwa byagurishijwe',
      'no_ratings_yet': 'Nta manota yabonetse',
    },
  };

  String get(String key) {
    return _translations[locale.languageCode]?[key] ??
        _translations['en']?[key] ??
        key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'fr', 'rw'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}

class LocaleProvider extends ChangeNotifier {
  Locale _locale = const Locale('en');

  Locale get locale => _locale;

  String get languageName {
    switch (_locale.languageCode) {
      case 'fr': return 'Français';
      case 'rw': return 'Kinyarwanda';
      default: return 'English';
    }
  }

  void setLocale(Locale locale) {
    _locale = locale;
    notifyListeners();
  }
}